import { AiTool } from './types';

export const AI_TOOLS_DATA: AiTool[] = [
    {category: "AI 챗봇 / 대화형 AI", name: "Claude", url: "https://claude.ai/", description: "Anthropic에서 개발한 AI로, 더 안전하고 정직하며 유용한 대화에 중점을 둡니다.", memo: "LLM중 맥락을 가장 잘 이해함.", rating: 5, plan: null},
    {category: "AI 챗봇 / 대화형 AI", name: "Gemini", url: "https://gemini.google.com/", description: "Google의 멀티모달 AI. 텍스트, 이미지, 오디오, 비디오 등 다양한 정보를 이해하고 처리합니다.", memo: "유밥 회사계정은 유료플랜", rating: 4.5, plan: null},
    {category: "AI 챗봇 / 대화형 AI", name: "Grok", url: "https://grok.com/", description: "xAI가 개발한 AI. 최신 정보에 강하고, 유머 감각과 개성 있는 답변을 제공하는 것이 특징입니다.", memo: "무제한 사용가능", rating: 4.5, plan: null},
    {category: "AI 챗봇 / 대화형 AI", name: "ChatGPT", url: "https://chatgpt.com/", description: "OpenAI의 대표적인 대화형 AI. 글쓰기, 번역, 코딩, 창의적인 작업 등 범용성이 뛰어납니다.", memo: "", rating: 4, plan: null},
    {category: "AI 챗봇 / 대화형 AI", name: "Qwen", url: "https://chat.qwen.ai/", description: "Alibaba Cloud에서 개발한 대규모 언어 모델 기반 챗봇입니다.", memo: "중국산이지만 무제한으로 사용가능 (이미지/영상 생성도 무제한)", rating: 4, plan: '완전무료'},
    {category: "AI 챗봇 / 대화형 AI", name: "Wrtn (뤼튼)", url: "https://wrtn.ai/", description: "한국의 대표적인 AI 포털 서비스로, 글쓰기, 광고 문구 제작 등 다양한 AI 도구를 제공합니다.", memo: "재미 있는 기능이 많음.", rating: 4, plan: null},
    {category: "AI 챗봇 / 대화형 AI", name: "Scira.ai", url: "https://scira.ai/", description: "과학 연구 및 논문 작성을 돕는 AI 기반 글쓰기 도구입니다.", memo: "LLM 서빙", rating: 4, plan: '완전무료'},
    {category: "AI 챗봇 / 대화형 AI", name: "Microsoft Copilot", url: "https://copilot.microsoft.com/", description: "Microsoft의 AI 비서. Windows, Office 등 다양한 자사 제품에 통합되어 생산성 향상을 돕습니다.", memo: "무제한 사용가능", rating: 3, plan: '완전무료'},
    {category: "AI 챗봇 / 대화형 AI", name: "CLOVA X", url: "https://clova-x.naver.com/", description: "Naver의 초거대 AI 모델을 기반으로 한 대화형 AI 서비스입니다.", memo: "한국산 성능이 슬픔.", rating: 1, plan: '완전무료'},
    {category: "AI 챗봇 / 대화형 AI", name: "ALAN", url: "https://alan.est.ai/", description: "이스트소프트에서 제공하는 AI 서비스로, 챗봇 및 문서 요약 등의 기능을 제공합니다.", memo: "한국산 클로바X와 큰 차이 없음.", rating: 1, plan: '완전무료'},
    {category: "AI 챗봇 / 대화형 AI", name: "DeepSeek", url: "https://chat.deepseek.com/", description: "DeepSeek AI에서 개발한 AI 챗봇으로, 특히 코딩과 수학 분야에 강점을 보입니다.", memo: "보안문제로 비추", rating: 0, plan: '완전무료'},
    {category: "AI 검색", name: "oo.ai", url: "https://oo.ai/", description: "인공지능 기반의 창의적인 글쓰기 및 대화형 AI 플랫폼입니다.", memo: "무료 무제한 (요즘은 구글보다 많이 사용)", rating: 4, plan: '완전무료'},
    {category: "AI 검색", name: "Perplexity AI", url: "https://www.perplexity.ai/", description: "출처를 함께 제공하는 대화형 AI 검색 엔진으로, 정확하고 신뢰도 높은 답변을 지향합니다.", memo: "검색 정리는 훌륭한데, 무료플랜은 몇번 못씀.", rating: 4, plan: null},
    {category: "AI 검색", name: "Genspark", url: "https://www.genspark.ai/", description: "AI 기반의 검색 및 에이전트 기능 강화", memo: "다양한 에이전트 기능으로 쓸모가 많지만 유료 플랜 에 해당", rating: 4, plan: null},
    {category: "AI 검색", name: "Felo AI", url: "https://felo.ai/search", description: "실시간 통역 및 번역에 특화된 AI 검색 및 대화 서비스입니다.", memo: "무료 검색 oo.ai와 같은 포지션.", rating: 4, plan: '완전무료'},
    {category: "AI 검색", name: "Naver Cue:", url: "https://search.naver.com/search.naver?query=Cue%3A", description: "Naver의 생성형 AI 검색 서비스", memo: "비추", rating: 1, plan: '완전무료'},
    {category: "개발 도구", name: "Windsurf", url: "https://windsurf.ai/", description: "AI 기반 브라우저 어시스턴트로, 웹페이지 요약, 정보 추출, 콘텐츠 생성 등 브라우징 경험을 향상시켜 생산성을 높여줍니다.", memo: "웹 서핑 중 정보 정리에 유용합니다.", rating: 4, plan: null},
    {category: "자동화 플랫폼", name: "Make", url: "https://www.make.com/", description: "코딩 없이 다양한 앱과 서비스를 연결하여 워크플로우를 시각적으로 자동화하는 플랫폼입니다.", memo: "UI가 편함.", rating: 4, plan: null},
    {category: "자동화 플랫폼", name: "Zapier", url: "https://zapier.com/", description: "가장 널리 쓰이는 웹 앱 자동화 도구 중 하나로, 수천 개의 앱을 연동하여 작업을 자동화합니다.", memo: "가장 호환성이 좋음.", rating: 4, plan: null},
    {category: "자동화 플랫폼", name: "n8n.io", url: "https://n8n.io/", description: "소스 코드가 공개된 워크플로우 자동화 도구로, 직접 서버에 설치하여 사용할 수도 있습니다.", memo: "오픈소스로 서버를 만들면 무료로 사용가능", rating: 4, plan: null},
    {category: "AI 연구", name: "NotebookLM", url: "https://notebooklm.google.com/", description: "Google의 AI 기반 연구 및 글쓰기 보조 도구. 사용자가 업로드한 자료를 기반으로 답변합니다.", memo: "데이터 정리에 훌륭함. (유밥 회사계정은 유료플랜)", rating: 5, plan: null},
    {category: "AI 연구", name: "Hugging Face", url: "https://huggingface.co/", description: "AI 모델, 데이터셋, 데모를 공유하는 세계 최대의 머신러닝 커뮤니티 및 플랫폼입니다.", memo: "오픈소스 AI모델", rating: 5, plan: '완전무료'},
    {category: "AI 연구", name: "Google AI Studio", url: "https://aistudio.google.com/", description: "개발자들이 Google의 최신 생성형 AI 모델(Gemini 등)을 활용하여 앱을 만들 수 있는 도구입니다.", memo: "Chat / 멀티모달Chat / 이미지 / 영상 / 앱생성 / 음상 / 음악 생성… AI로 할 수 있는 거의 모든 것을 무료로 해볼 수 있음.", rating: 5, plan: '완전무료'},
    {category: "AI 연구", name: "GitHub Marketplace", url: "https://github.com/marketplace?type=models", description: "GitHub에서 제공하는 AI 모델 마켓플레이스로, 다양한 머신러닝 모델을 찾고 사용할 수 있습니다.", memo: "다양한 LLM모델을 무료로 사용할 수 있음.", rating: 5, plan: '완전무료'},
    {category: "AI 연구", name: "Lilys.ai", url: "https://lilys.ai/", description: "AI 기반의 지식 관리 및 연구 도구입니다.", memo: "NotebookLM 보다 먼저 나왔지만 지금은 그냥 NotebookLM을 씀.", rating: 4, plan: null},
    {category: "AI 연구", name: "DeepWiki", url: "https://deepwiki.com/", description: "AI를 활용하여 지식을 구축하고 공유하는 위키 플랫폼입니다.", memo: "깃허브의 내용을 마크다운형식으로 정리해줌.", rating: 4, plan: '완전무료'},
    {category: "디자인 / 프로토타이핑", name: "Stitch", url: "https://stitch.withgoogle.com/", description: "(실험적) Google의 생성형 AI 시퀀스 제작을 위한 연구 프로젝트입니다.", memo: "자연어 UI생성", rating: 4, plan: null},
    {category: "AI 창작 도구", name: "Artbot.site", url: "https://artbot.site/create", description: "다양한 AI 모델을 활용하여 이미지를 생성할 수 있는 사이트입니다.", memo: "무료 이미지 생성 (무제한)", rating: 5, plan: '완전무료'},
    {category: "AI 창작 도구", name: "Animon.ai", url: "https://www.animon.ai/explore", description: "AI를 통해 애니메이션 캐릭터나 영상을 생성하고 탐색하는 플랫폼입니다.", memo: "무료 영상 생성 (무제한)", rating: 5, plan: null},
    {category: "AI 창작 도구", name: "Google Vids", url: "https://workspace.google.com/products/vids/", description: "Google Workspace에 포함된 AI 비디오 제작 앱. 비즈니스용 스토리보드, 제작, 편집을 지원합니다.", memo: "", rating: 4, plan: null},
    {category: "AI 창작 도구", name: "MusicFX", url: "https://labs.google/fx/ko/tools/music-fx", description: "Google에서 제공하는 텍스트 기반 음악 생성 AI 도구입니다.", memo: "음악 생성", rating: 4, plan: null},
    {category: "AI 창작 도구", name: "Suno", url: "https://suno.com/home", description: "텍스트 프롬프트를 기반으로 보컬을 포함한 완성도 높은 노래를 생성하는 AI 음악 도구입니다.", memo: "가장 유명한 AI 음악 생성 도구", rating: 4, plan: null},
    {category: "AI 창작 도구", name: "Mureka", url: "https://www.mureka.ai/", description: "AI를 활용하여 음악을 생성, 편집, 리믹스할 수 있는 플랫폼입니다.", memo: "Suno와 유사한 음악 생성 AI", rating: 4, plan: null},
    {category: "AI 뉴스 / 커뮤니티", name: "Hada News", url: "https://news.hada.io/", description: "개발자들을 위한 IT 기술 뉴스 공유 사이트로, AI 관련 소식이 자주 올라옵니다.", memo: "국내/해외 뉴스를 한글로 요약해줌.", rating: 5, plan: '완전무료'},
    {category: "AI 뉴스 / 커뮤니티", name: "AI타임스", url: "https://www.aitimes.com/", description: "대한민국 대표 AI 전문 언론사로, 국내외 AI 관련 뉴스와 정보를 다룹니다.", memo: "", rating: 4, plan: '완전무료'},
    {category: "AI 뉴스 / 커뮤니티", name: "SK devocean", url: "https://devocean.sk.com/tech", description: "SK 그룹의 개발자 커뮤니티로, AI를 포함한 최신 기술 동향과 정보를 공유합니다.", memo: "", rating: 4, plan: '완전무료'},
    {category: "개발 도구", name: "Cursor", url: "https://cursor.sh/", description: "VS Code를 기반으로 AI 기능을 통합한 코드 에디터로, 페어 프로그래밍, 코드 생성 및 수정, 디버깅 등을 AI와 함께 수행할 수 있습니다.", memo: "AI 기반 코딩에 매우 강력한 기능을 제공합니다.", rating: 5, plan: null},
    {category: "개발 도구", name: "VS Code", url: "https://code.visualstudio.com/", description: "Microsoft에서 개발한 무료 오픈소스 코드 에디터. 확장성이 뛰어나 다양한 언어와 프레임워크를 지원합니다.", memo: "가장 널리 사용되는 코드 에디터.", rating: 5, plan: '완전무료'},
    {category: "개발 도구", name: "Docker", url: "https://www.docker.com/", description: "애플리케이션을 컨테이너화하여 개발, 배포, 실행을 단순화하는 플랫폼입니다.", memo: "서버 환경 구성을 쉽게 만들어줍니다.", rating: 5, plan: null},
    {category: "개발 도구", name: "Git", url: "https://git-scm.com/", description: "분산 버전 관리 시스템으로, 소스 코드의 버전을 효과적으로 관리하고 협업을 돕습니다.", memo: "개발자 협업의 필수품.", rating: 5, plan: '완전무료'},
    {category: "디자인 / 프로토타이핑", name: "Figma", url: "https://www.figma.com/", description: "웹 기반의 협업 인터페이스 디자인 도구. UI/UX 디자인, 프로토타이핑, 디자인 시스템 구축에 사용됩니다.", memo: "디자이너와 개발자 간의 협업에 탁월합니다.", rating: 5, plan: null},
    {category: "API / 테스트", name: "Postman", url: "https://www.postman.com/", description: "API를 설계, 구축, 테스트하고 협업하기 위한 API 플랫폼입니다.", memo: "API 개발 및 테스트 시간을 단축시켜 줍니다.", rating: 4.5, plan: null}
];

export const CATEGORIES = ['전체', ...new Set(AI_TOOLS_DATA.map(tool => tool.category))];